# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9b5c1591c7b91ef4313f2ccb801051ae3378f1a766fd2f185e3eb4eea5cb645e2cf2a88c539079656e5814d520cd9f1d2c28ba94c6b652c37679082b0fa25316

test:
  secret_key_base: 1fe6f281bfde8e277f76cbea3bfe7dd1d4ca9cee01f15f9769dd2fee38341142a34472724739d2b5c8ad3003a1325785713fd8adc41fc9e07689c6a90ae3de86

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
